# Generated by Django 4.2.8 on 2023-12-19 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('title', models.CharField(choices=[('CEO', 'CEO'), ('D_CEO', 'Deputy CEO'), ('REG_MAN', 'Regional Manager'), ('TER_MAN', 'Territorial Manager'), ('DTER_MAN', 'Deputy Territorial Manager'), ('HON', 'Head of Network'), ('PHARM', 'Pharmacist')], max_length=10)),
                ('hire_date', models.DateField(default=datetime.datetime(2023, 12, 19, 12, 16, 20, 260095, tzinfo=datetime.timezone.utc))),
                ('email', models.EmailField(max_length=254)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('boss', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
