# Generated by Django 4.2.8 on 2023-12-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_hire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='title',
            new_name='post',
        ),
    ]
