# Generated by Django 4.2.8 on 2023-12-19 14:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_hire_date_alter_employee_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 12, 19))]),
        ),
    ]
