# Generated by Django 4.2.8 on 2023-12-20 00:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_hire_date_alter_employee_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today)]),
        ),
    ]
