# Generated by Django 4.2.8 on 2023-12-20 08:19

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employee.employee', verbose_name='boss ID'),
        ),
    ]
